# controller_frequency: 3
# TrajectoryPlannerROS:
#   # max_vel_x: 0.35
#   max_vel_x: 0.45
#   min_vel_x: -0.45
#   #min_vel_x: -0.35
#   # max_vel_theta: 0.7
#   max_vel_theta: 0.5
#   # min_vel_theta: -0.7
#   min_vel_theta: -0.5
#   #min_in_place_vel_theta: 0.1
#   min_in_place_vel_theta: 0.5

#   #acc_lim_theta: 0.7
#   #acc_lim_x: 0.7
#   #acc_lim_Y: 0.0

#   holonomic_robot: false


#   meter_scoring: true

#   # xy_goal_tolerance: 0.07
#   xy_goal_tolerance: 0.20
# #  yaw_goal_tolerance: 0.05
#   yaw_goal_tolerance: 0.5
#   oscillation_reset_dist: 0.05
#   sim_time: 5.0
#   sim_granularity: 0.05
#   angular_sim_granularity: 0.3
#   global_frame_id: odom
#   prune_plan: true

controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 1.2 #0.5 #0.4
  min_vel_x: 0.02 # 0.05 #0.1
  max_vel_theta: 0.7 # 1
  min_vel_theta: -0.7 #-1
  min_in_place_vel_theta: 0.5 #0.5

  acc_lim_theta: 0.2
  acc_lim_x: 0.11
  acc_lim_Y: 0.11

  holonomic_robot: false

  meter_scoring: true

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.6

  sim_time: 4.0
  sim_granularity: 0.05
  # angular_sim_granularity: 0.2