# global_costmap:
#   global_frame: map
#   update_frequency: 1.0
#   publish_frequency: 0.5
#   transform_tolerance: 0.5
#   robot_base_frame: base_link
#   update_frequency: 2.0
#   publish_frequency: 1.0
#   transform_tolerance: 0.8
#   static_map: false
#   resolution: 0.025
#   width: 3.4 #3.4
#   height: 3.4 #3.4
global_costmap:
  global_frame: map
  # update_frequency: 5.0
  # publish_frequency: 5.0
  # transform_tolerance: 0.8
  update_frequency: 1.0
  publish_frequency: 1.0
  transform_tolerance: 0.8
  static_map: false
  resolution: 0.05
  width: 5 #3.4
  height: 5 #3.4
