# local_costmap:
#   global_frame: odom
#   robot_base_frame: base_link
#   update_frequency: 1
#   publish_frequency: 2.0
#   transform_tolerance: 0.5
  
#   static_map: false
#   rolling_window: true
#   resolution: 0.025
#   inflation_radius: 0.10
#   width: 1.0
#   height: 1.0
#   # width: 5
#   # height: 5

#  # plugins:
#     #- {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}

#   obstacle_layer:
#     observation_sources: laser_scan_sensor
#     laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}


local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 0.8
  
  static_map: false
  rolling_window: true
  resolution: 0.05
  inflation_radius: 0.15
  width: 1.0
  height: 1.0
  # width: 5
  # height: 5

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}

  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}