apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: "ros-master"
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: ros-master
    spec:
      containers:
      - name: service 
        image: matheusdutra0207/master-ros:v1
        ports:
        - containerPort: 11311        
        args:
          - roscore
        imagePullPolicy: IfNotPresent
      
---

apiVersion: v1
kind: Service
metadata:
  name: ros-master
  namespace: default
spec:
  type: NodePort
  selector:
    app: ros-master
  ports:
    - name: master
      protocol: TCP
      port: 11311
      targetPort: 11311
      nodePort: 30015