apiVersion: v1
kind: ConfigMap
metadata:
  name: amcl-config
  namespace: default
data:
  config: |-
    tf_broadcast: True
    # Overall filter parameters
    use_map_topic:        false      # false
    min_particles:        100       # 100,500
    max_particles:        10000     # 5000
    kld_err:              0.01      # 0.01, 0.05
    kld_z:                0.99      # 0.99
    update_min_d:         0.000       # 0.2
    update_min_a:         0.000    # 0.5235
    resample_interval:    2         # 2, 1
    transform_tolerance:  0.1       # 0.1, 0.2
    recovery_alpha_slow:  0.001     # 0.0, 0.0, 0.001
    recovery_alpha_fast:  0.1       # 0.0, 0.0, 0.1
    initial_pose_x:       0.0       # 0.0
    initial_pose_y:       0.0       # 0.0
    initial_pose_a:       0.0       # 0.0
    initial_cov_xx:       0.25      # 0.25
    initial_cov_yy:       0.25      # 0.25
    initial_cov_aa:       0.06853   # 0.06853 
    gui_publish_rate:     10.0      # -1.0, 10
    save_pose_rate:       0.5       # 0.5
    first_map_only:       false     # false
    # Laser Model Parameters 
    laser_min_range:            -1.0   # -1.0
    laser_max_range:            -1.0   # -1.0
    laser_max_beams:            30    # 180
    laser_z_hit:                0.3   # 0.95, 0.5
    laser_z_short:              0.05    # 0.1,  0.05
    laser_z_max:                0.05   # 0.05 
    laser_z_rand:               0.5   # 0.05, 0.5
    laser_sigma_hit:            0.2    # 0.2   
    laser_lambda_short:         0.1    # 0.1
    laser_likelihood_max_dist:  2.0    # 2.0
    laser_model_type:           likelihood_field
    # Odometery model parameters
    odom_model_type:  diff-corrected
    odom_alpha1:      0.5    # 0.2 rr
    odom_alpha2:      0.25   # 0.2 rt
    odom_alpha3:      0.6    # 0.2,0.8 tt
    odom_alpha4:      0.25   # 0.2 tr
    odom_alpha5:      0.2    # 0.2,0.1
    odom_frame_id:    odom 
    base_frame_id:    base_link 
    global_frame_id:  map 

---

apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: "amcl-package"
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: amcl-package 
    spec:
      containers:
      - name: service 
        image: matheusdutra0207/amcl-ros:v2
        args:
          - roslaunch 
          - amcl.launch
        env:
        - name: ROS_MASTER_URI
          value: http://10.10.3.188:30015
        - name: ROS_IP
          value: 10.10.3.188
        imagePullPolicy: Always
        volumeMounts:
          - name: amcl-config-volume
            mountPath: /opt/ros/config
      volumes:
      - name: amcl-config-volume
        configMap:
          name: amcl-config
          items:
          - key: config
            path: amcl_template.yaml
      hostNetwork: true