apiVersion: v1
kind: ConfigMap
metadata:
  name: robot-localization-config
  namespace: default
data:
  config: |-
    publish_tf: true
    frequency: 10
    two_d_mode: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map
    transform_time_offset: 1
    smooth_lagged_data: true
    dynamic_process_noise_covariance: false

    odom0: odrive/odom
    odom0_config: [false, false, false,
                    false, false, false,
                    true,  true,  true,
                    false, false, true,
                    false, false, false]
    odom0_queue_size: 10
    odom0_nodelay: true
    odom0_differential: false
    odom0_relative: false

    pose0: is/Robis  
    pose0_config: [true,  true,  false,
                  false, false, true,
                  false, false, false,
                  false, false, false,
                  false, false, false]

    process_noise_covariance: [0.0008, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0.0008, 0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0.0008, 0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0.00008, 0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0.00008, 0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0.0003, 0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0.000208, 0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0.000208, 0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0.00008, 0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0.00008, 0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0.00008, 0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0.00008, 0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0.00008, 0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0.00008, 0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0.000108]
    initial_estimate_covariance: [1e-5, 0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    1e-5, 0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    1e-9, 0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    1e-9, 0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    1e-6, 0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    1e-9, 0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    1e-9, 0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    1e-9, 0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9,  0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     1e-9,  0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     1e-9,  0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     1e-9, 0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    1e-9, 0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    1e-9]

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "robot-localization-package"
spec:
  selector:
    matchLabels:
      app:  "robot-localization-package"
  replicas: 1 
  template:
    metadata:
      labels:
        app: robot-localization-package 
    spec:
      nodeSelector:
        kubernetes.io/hostname: thor          
      containers:
      - name: service 
        image: matheusdutra0207/robot-localization-ros:v2
        args:
          - roslaunch 
          - ekf.launch
        env:
        - name: ROS_MASTER_URI
          value: http://10.20.5.2:30015
        - name: ROS_IP
          value: 10.20.5.2
        imagePullPolicy: Always
        volumeMounts:
          - name: robot-localization-config-volume
            mountPath: /opt/ros/config
      volumes:
      - name: robot-localization-config-volume
        configMap:
          name: robot-localization-config
          items:
          - key: config
            path: ekf_template.yaml
      hostNetwork: true
        